export const all_questions = [
  {
    id: 1,
    japanese: "はい",
    options: ["Yes", "No", "Maybe", "Sometimes"],
    answer: "Yes",
  },
  {
    id: 2,
    japanese: "いいえ",
    options: ["Yes", "No", "Maybe", "Sometimes"],
    answer: "No",
  },
  {
    id: 3,
    japanese: "こんにちは",
    options: ["Goodbye", "Hello", "Thank you", "I’m Sorry"],
    answer: "Hello",
  },
  {
    id: 4,
    japanese: "じゃね",
    options: ["Thank you", "I’m Sorry", "Goodbye", "Excuse me"],
    answer: "Goodbye",
  },
  {
    id: 5,
    japanese: "ありがとう",
    options: ["Yes", "No", "Thank you", "Excuse me"],
    answer: "Thank you",
  },
  {
    id: 6,
    japanese: "ごめんなさい",
    options: ["Yes", "No", "Thank you", "I’m Sorry"],
    answer: "I’m Sorry",
  },
  {
    id: 7,
    japanese: "すみません",
    options: ["Yes", "No", "Excuse me", "Thank you"],
    answer: "Excuse me",
  },
  {
    id: 8,
    japanese: "私",
    options: ["You", "He", "She", "I"],
    answer: "I",
  },
  {
    id: 9,
    japanese: "あなた",
    options: ["This", "That", "He", "You"],
    answer: "You",
  },
  {
    id: 10,
    japanese: "これ",
    options: ["This", "That", "He", "She"],
    answer: "This",
  },
  {
    id: 11,
    japanese: "それ",
    options: ["This", "That", "He", "She"],
    answer: "That",
  },
  {
    id: 12,
    japanese: "彼",
    options: ["He", "She", "I", "You"],
    answer: "He",
  },
  {
    id: 13,
    japanese: "彼女",
    options: ["He", "She", "I", "You"],
    answer: "She",
  },
  {
    id: 14,
    japanese: "彼ら",
    options: ["I", "You", "They", "We"],
    answer: "They",
  },
  {
    id: 15,
    japanese: "いち",
    options: ["One", "Two", "Three", "Four"],
    answer: "One",
  },
  {
    id: 16,
    japanese: "に",
    options: ["One", "Two", "Three", "Four"],
    answer: "Two",
  },
  {
    id: 17,
    japanese: "さん",
    options: ["Two", "Three", "Four", "Five"],
    answer: "Three",
  },
  {
    id: 18,
    japanese: "し",
    options: ["Three", "Four", "Five", "Six"],
    answer: "Four",
  },
  {
    id: 19,
    japanese: "ご",
    options: ["Four", "Five", "Six", "Seven"],
    answer: "Five",
  },
  {
    id: 20,
    japanese: "ろく",
    options: ["Five", "Six", "Seven", "Eight"],
    answer: "Six",
  },
  {
    id: 21,
    japanese: "なな",
    options: ["Six", "Seven", "Eight", "Nine"],
    answer: "Seven",
  },
  {
    id: 22,
    japanese: "はち",
    options: ["Seven", "Eight", "Nine", "Ten"],
    answer: "Eight",
  },
  {
    id: 23,
    japanese: "く",
    options: ["Eight", "Nine", "Ten", "One"],
    answer: "Nine",
  },
  {
    id: 24,
    japanese: "じゅう",
    options: ["Nine", "Ten", "One", "Two"],
    answer: "Ten",
  },
  {
    id: 25,
    japanese: "今日",
    options: ["Today", "Tomorrow", "Yesterday", "Now"],
    answer: "Today",
  },
  {
    id: 26,
    japanese: "明日",
    options: ["Today", "Tomorrow", "Yesterday", "Now"],
    answer: "Tomorrow",
  },
  {
    id: 27,
    japanese: "昨日",
    options: ["Today", "Tomorrow", "Yesterday", "Now"],
    answer: "Yesterday",
  },
  {
    id: 28,
    japanese: "今",
    options: ["Today", "Tomorrow", "Yesterday", "Now"],
    answer: "Now",
  },
  {
    id: 29,
    japanese: "前に",
    options: ["Before", "Later", "Yesterday", "Now"],
    answer: "Before",
  },
  {
    id: 30,
    japanese: "後で",
    options: ["Before", "Later", "Yesterday", "Now"],
    answer: "Later",
  },
  {
    id: 31,
    japanese: "する",
    options: ["To do", "To be", "To become", "There is (inanimate)"],
    answer: "To do",
  },
  {
    id: 32,
    japanese: "です",
    options: ["To do", "To be", "To become", "There is (inanimate)"],
    answer: "To be",
  },
  {
    id: 33,
    japanese: "なる",
    options: ["To do", "To be", "To become", "There is (inanimate)"],
    answer: "To become",
  },
  {
    id: 34,
    japanese: "ある",
    options: ["To do", "To be", "To become", "There is (inanimate)"],
    answer: "There is (inanimate)",
  },
  {
    id: 35,
    japanese: "いる",
    options: ["To do", "To be", "To become", "There is (living)"],
    answer: "There is (living)",
  },
  {
    id: 36,
    japanese: "行く",
    options: ["To go", "To come", "To see", "To eat"],
    answer: "To go",
  },
  {
    id: 37,
    japanese: "言う",
    options: ["To do", "To say", "To become", "There is (inanimate)"],
    answer: "To say",
  },
  {
    id: 38,
    japanese: "見る",
    options: ["To do", "To be", "To see", "There is (inanimate)"],
    answer: "To see",
  },
  {
    id: 39,
    japanese: "来る",
    options: ["To come", "To go", "To say", "To eat"],
    answer: "To come",
  },
  {
    id: 40,
    japanese: "食べる",
    options: ["To do", "To be", "To see", "To eat"],
    answer: "To eat",
  },
  {
    id: 41,
    japanese: "本",
    options: ["Book", "Bed", "Birthday", "Clock"],
    answer: "Book",
  },
  {
    id: 42,
    japanese: "ベッド",
    options: ["Bed", "Book", "Name", "University"],
    answer: "Bed",
  },
  {
    id: 43,
    japanese: "誕生日",
    options: ["Birthday", "English (language)", "Telephone", "Dog"],
    answer: "Birthday",
  },
  {
    id: 44,
    japanese: "時計",
    options: ["Watch / Clock", "Clothes", "Cat", "Computer"],
    answer: "Watch / Clock",
  },
  {
    id: 45,
    japanese: "名前",
    options: ["Name", "Bus", "White", "Bed"],
    answer: "Name",
  },
  {
    id: 46,
    japanese: "きれい",
    options: ["Beautiful", "Black", "University", "Telephone"],
    answer: "Beautiful",
  },
  {
    id: 47,
    japanese: "黒い",
    options: ["Black", "English (language)", "Dog", "Clothes"],
    answer: "Black",
  },
  {
    id: 48,
    japanese: "白い",
    options: ["White", "Cat", "Computer", "Birthday"],
    answer: "White",
  },
  {
    id: 49,
    japanese: "英語",
    options: ["English (language)", "Bus", "Watch / Clock", "Name"],
    answer: "English (language)",
  },
  {
    id: 50,
    japanese: "大学",
    options: ["University", "Bed", "Telephone", "Beautiful"],
    answer: "University",
  },
  {
    id: 51,
    japanese: "電話",
    options: ["Telephone", "Book", "Cat", "Black"],
    answer: "Telephone",
  },
  {
    id: 52,
    japanese: "バス",
    options: ["Bus", "Name", "White", "Watch / Clock"],
    answer: "Bus",
  },
  {
    id: 53,
    japanese: "猫",
    options: ["Cat", "Computer", "Bed", "Birthday"],
    answer: "Cat",
  },
  {
    id: 54,
    japanese: "犬",
    options: ["Dog", "Beautiful", "University", "Telephone"],
    answer: "Dog",
  },
  {
    id: 55,
    japanese: "コンピュータ",
    options: ["Computer", "Black", "Book", "Bed"],
    answer: "Computer",
  },
  {
    id: 56,
    japanese: "服",
    options: ["Clothes", "Watch / Clock", "English (language)", "Name"],
    answer: "Clothes",
  },
  {
    id: 57,
    japanese: "コーヒー",
    options: ["Coffee", "Tea", "Water", "Milk"],
    answer: "Coffee",
  },
  {
    id: 58,
    japanese: "パン",
    options: ["Bread", "Rice", "Noodles", "Pasta"],
    answer: "Bread",
  },
  {
    id: 59,
    japanese: "ビール",
    options: ["Beer", "Wine", "Soda", "Juice"],
    answer: "Beer",
  },
  {
    id: 60,
    japanese: "昼ご飯",
    options: ["Lunch", "Breakfast", "Dinner", "Snack"],
    answer: "Lunch",
  },
  {
    id: 61,
    japanese: "夕食",
    options: ["Dinner", "Lunch", "Breakfast", "Snack"],
    answer: "Dinner",
  },
  {
    id: 62,
    japanese: "食べ物",
    options: ["Food", "Drink", "Clothing", "Electronics"],
    answer: "Food",
  },
  {
    id: 63,
    japanese: "飲み物",
    options: ["Beverage", "Food", "Clothing", "Electronics"],
    answer: "Beverage",
  },
  {
    id: 64,
    japanese: "果物",
    options: ["Fruit", "Vegetable", "Meat", "Dairy"],
    answer: "Fruit",
  },
  {
    id: 65,
    japanese: "男の子",
    options: ["Boy", "Girl", "Child", "Mother"],
    answer: "Boy",
  },
  {
    id: 66,
    japanese: "女の子",
    options: ["Boy", "Girl", "Child", "Mother"],
    answer: "Girl",
  },
  {
    id: 67,
    japanese: "子供",
    options: ["Boy", "Girl", "Child", "Mother"],
    answer: "Child",
  },
  {
    id: 68,
    japanese: "母",
    options: ["Boy", "Girl", "Child", "Mother"],
    answer: "Mother",
  },
  {
    id: 69,
    japanese: "父",
    options: ["Boy", "Girl", "Child", "Father"],
    answer: "Father",
  },
  {
    id: 70,
    japanese: "友達",
    options: ["Boy", "Girl", "Child", "Friend"],
    answer: "Friend",
  },
  {
    id: 71,
    japanese: "学生",
    options: ["Student", "Teacher", "Boy", "Girl"],
    answer: "Student",
  },
  {
    id: 72,
    japanese: "先生",
    options: ["Student", "Teacher", "Boy", "Girl"],
    answer: "Teacher",
  },
  {
    id: 73,
    japanese: "川",
    options: ["Mountain", "Flower", "Fish", "River"],
    answer: "River",
  },
  {
    id: 74,
    japanese: "花",
    options: ["Sky", "Fish", "Mountain", "Flower"],
    answer: "Flower",
  },
  {
    id: 75,
    japanese: "魚",
    options: ["Sky", "Fish", "Mountain", "Flower"],
    answer: "Fish",
  },
  {
    id: 76,
    japanese: "空",
    options: ["Sky", "Fish", "Mountain", "Flower"],
    answer: "Sky",
  },
  {
    id: 77,
    japanese: "山",
    options: ["River", "Mountain", "Flower", "Fish"],
    answer: "Mountain",
  },
  {
    id: 78,
    japanese: "雨",
    options: ["Fish", "Rain", "Sky", "Mountain"],
    answer: "Rain",
  },
  {
    id: 79,
    japanese: "毎日",
    options: ["Every day", "Every week", "Every month", "Every year"],
    answer: "Every day",
  },
  {
    id: 80,
    japanese: "毎週",
    options: ["Every week", "Every day", "Every month", "Every year"],
    answer: "Every week",
  },
  {
    id: 81,
    japanese: "午前",
    options: ["Morning", "Afternoon", "Evening", "Night"],
    answer: "Morning",
  },
  {
    id: 82,
    japanese: "午後",
    options: ["Afternoon", "Morning", "Evening", "Night"],
    answer: "Afternoon",
  },
  {
    id: 83,
    japanese: "月曜日",
    options: ["Monday", "Tuesday", "Wednesday", "Thursday"],
    answer: "Monday",
  },
  {
    id: 84,
    japanese: "火曜日",
    options: ["Tuesday", "Monday", "Wednesday", "Thursday"],
    answer: "Tuesday",
  },
  {
    id: 85,
    japanese: "水曜日",
    options: ["Wednesday", "Monday", "Tuesday", "Thursday"],
    answer: "Wednesday",
  },
  {
    id: 86,
    japanese: "木曜日",
    options: ["Thursday", "Monday", "Tuesday", "Wednesday"],
    answer: "Thursday",
  },
  {
    id: 87,
    japanese: "金曜日",
    options: ["Friday", "Monday", "Tuesday", "Wednesday"],
    answer: "Friday",
  },
  {
    id: 88,
    japanese: "土曜日",
    options: ["Saturday", "Sunday", "Monday", "Friday"],
    answer: "Saturday",
  },
  {
    id: 89,
    japanese: "日曜日",
    options: ["Sunday", "Saturday", "Monday", "Friday"],
    answer: "Sunday",
  },
  {
    id: 90,
    japanese: "今年",
    options: ["This year", "Last year", "Next year", "Every year"],
    answer: "This year",
  },
  {
    id: 91,
    japanese: "耳",
    options: ["Eye", "Mouth", "Ear", "Hand"],
    answer: "Ear",
  },
  {
    id: 92,
    japanese: "手",
    options: ["Foot", "Hand", "Eye", "Mouth"],
    answer: "Hand",
  },
  {
    id: 93,
    japanese: "足",
    options: ["Mouth", "Ear", "Foot", "Hand"],
    answer: "Foot",
  },
  {
    id: 94,
    japanese: "目",
    options: ["Ear", "Foot", "Eye", "Hand"],
    answer: "Eye",
  },
  {
    id: 95,
    japanese: "口",
    options: ["Eye", "Mouth", "Ear", "Foot"],
    answer: "Mouth",
  },
  {
    id: 96,
    japanese: "顔",
    options: ["Mouth", "Ear", "Foot", "Face"],
    answer: "Face",
  },
  {
    id: 97,
    japanese: "ウケる",
    options: ["Funny", "Super", "Uncool", "Gross"],
    answer: "Funny",
  },
  {
    id: 98,
    japanese: "超",
    options: ["Funny", "Super", "Uncool", "Gross"],
    answer: "Super",
  },
  {
    id: 99,
    japanese: "ださい",
    options: ["Funny", "Super", "Uncool", "Gross"],
    answer: "Uncool",
  },
  {
    id: 100,
    japanese: "キモい",
    options: ["Funny", "Super", "Uncool", "Gross"],
    answer: "Gross",
  },
];

export const random_ten_questions = (all_questions) => {
  // Create a deep copy of the questions array
  const chosen_questions = JSON.parse(JSON.stringify(all_questions))
    // Randomizes and chooses 10 questions from the bank
    .sort(() => Math.random() - 0.5)
    .slice(0, 10);
  chosen_questions.forEach((question) => {
    // Randomizes the options array of each of the 10 chosen questions
    question.options.sort(() => Math.random() - 0.5);
  });
  return chosen_questions;
};


